---
name: Lint and build

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.*
          cache: pip
          cache-dependency-path: ./.github/workflows/build_publish.yml

      - name: Install pre-commit
        run: python -m pip install pre-commit

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit checks
        run: pre-commit run --all-files
        env:
          SKIP: chktex-system,no-commit-to-branch

      - name: Build LaTeX PDF
        uses: xu-cheng/latex-action@v3
        with:
          pre_compile: tlmgr install chktex && chktex main.tex
          root_file: main.tex
          working_directory: ./latex/
